version: '3.3'
services:

  next-app:
    build: .  
    image: next-app
    ports:
      - "3000:3000"
    networks:
      - next
    
  nginx:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    volumes:
      - "nginx.conf:/etc/nginx/conf.d/nginx.conf"
    networks:
      - next
    depends-on:
      - next-app

networks:
  next:
    driver: bridge
