export const sampleNotifications = [
  {
    data: {
      notifications: [
        {
          createDate: "16 Nov 2023 04:55 PM",
          id: 2674,
          isRead: false,
          message: "#IN-8794761887 for $375.00 has been submitted by Artigem Contents",
          messageTemplate:
            "Invoice ${invoiceNumber} of ${invoiceAmount} is submitted for claim ${claimNumber} by vendor ${vendorName}",
          notificationParams: {
            isClaimNote: false,
            invoiceNumber: "IN-8794761887",
            invoiceId: 409,
            claimId: 1086,
            isItemNote: false,
            messageGrpId: null,
            claimNumber: "flow16112023",
            quoteNumber: null,
            message1: "An Invoice Has Been Submitted",
          },
          notificationPurpose: "ITEM INVOICE",
          sender: null,
          subject: {
            id: 8,
            subject: "INVOICE_SUBMITTED",
          },
          type: {
            id: 1,
            type: "ALERT",
          },
          insuredDetails: {
            address: {
              city: "New Jersey",
              completeAddress: "4327 Finwood Road, Piscataway, New Jersey, NJ, 08854",
              id: 85,
              state: {
                id: 31,
                state: "NJ",
                stateName: null,
                taxRate: 6.85,
                timeZone: "(UTC-5:00) Eastern Standard Time (EST)",
                noOfZipcodesWrtState: null,
                premiumValueWrtState: null,
                hoPolicyTypes: null,
                noOfHOPolicyTypeState: null,
              },
              streetAddressOne: "4327 Finwood Road",
              streetAddressTwo: "Piscataway",
              zipcode: "08854",
            },
            secondaryAddress: null,
            agentDetails: null,
            cellPhone: null,
            extension: null,
            dayTimePhone: null,
            email: "policy.holder@sakhaglobal.com",
            secondaryEmail: null,
            eveningTimePhone: null,
            firstName: "Gracie",
            lastName: "Smith",
            policyHolderId: 29,
            profilePicture: null,
            speedCheckVendorUrl: null,
            userRole: null,
            contactId: null,
          },
          page: null,
        },
        {
          createDate: "13 Nov 2023 09:37 PM",
          id: 2613,
          isRead: true,
          message: "#IN-3912263778 for $4.00 has been submitted by Artigem",
          messageTemplate:
            "Invoice ${invoiceNumber} of ${invoiceAmount} is submitted for claim ${claimNumber} by vendor ${vendorName}",
          notificationParams: {
            isClaimNote: false,
            invoiceNumber: "IN-3912263778",
            invoiceId: 396,
            claimId: 1039,
            isItemNote: false,
            messageGrpId: null,
            claimNumber: "CLM9112023",
            quoteNumber: null,
            message1: "An Invoice Has Been Submitted",
          },
          notificationPurpose: "ITEM INVOICE",
          sender: null,
          subject: {
            id: 8,
            subject: "INVOICE_SUBMITTED",
          },
          type: {
            id: 1,
            type: "ALERT",
          },
          insuredDetails: {
            address: {
              city: "New Jersey",
              completeAddress: "4327 Finwood Road, Piscataway, New Jersey, NJ, 08854",
              id: 85,
              state: {
                id: 31,
                state: "NJ",
                stateName: null,
                taxRate: 6.85,
                timeZone: "(UTC-5:00) Eastern Standard Time (EST)",
                noOfZipcodesWrtState: null,
                premiumValueWrtState: null,
                hoPolicyTypes: null,
                noOfHOPolicyTypeState: null,
              },
              streetAddressOne: "4327 Finwood Road",
              streetAddressTwo: "Piscataway",
              zipcode: "08854",
            },
            secondaryAddress: null,
            agentDetails: null,
            cellPhone: null,
            extension: null,
            dayTimePhone: null,
            email: "policy.holder@sakhaglobal.com",
            secondaryEmail: null,
            eveningTimePhone: null,
            firstName: "Gracie",
            lastName: "Smith",
            policyHolderId: 29,
            profilePicture: null,
            speedCheckVendorUrl: null,
            userRole: null,
            contactId: null,
          },
          page: null,
        },
        {
          createDate: "09 Nov 2023 09:27 PM",
          id: 2577,
          isRead: false,
          message: "#CLM9112024 has been submitted by ARTGM",
          messageTemplate:
            "Vendor Quote is created against assignment ${assignmentNumber} by vendor ${vendor}",
          notificationParams: {
            isClaimNote: false,
            claimId: 1043,
            isItemNote: false,
            assignmentNumber: "A2C57C6DF9DC",
            messageGrpId: null,
            claimNumber: "CLM9112024",
            quoteNumber: "QUOT-KA-1699545430629",
            message1: "A Quote Has Been Submitted",
          },
          notificationPurpose: "VENDOR QUOTE",
          sender: null,
          subject: {
            id: 35,
            subject: "QUOTE_CREATED",
          },
          type: {
            id: 1,
            type: "ALERT",
          },
          insuredDetails: {
            address: {
              city: null,
              completeAddress: "AZ, 87889",
              id: 2802,
              state: {
                id: 3,
                state: "AZ",
                stateName: null,
                taxRate: 8.25,
                timeZone: "(UTC-7:00) Mountain Standard Time (MST)",
                noOfZipcodesWrtState: null,
                premiumValueWrtState: null,
                hoPolicyTypes: null,
                noOfHOPolicyTypeState: null,
              },
              streetAddressOne: null,
              streetAddressTwo: null,
              zipcode: "87889",
            },
            secondaryAddress: null,
            agentDetails: null,
            cellPhone: null,
            extension: null,
            dayTimePhone: null,
            email: "xeyasa4986@undewp.com",
            secondaryEmail: null,
            eveningTimePhone: null,
            firstName: "Avinash",
            lastName: "Kumar",
            policyHolderId: 458,
            profilePicture: null,
            speedCheckVendorUrl: null,
            userRole: null,
            contactId: null,
          },
          page: null,
        },
        {
          createDate: "09 Nov 2023 09:10 PM",
          id: 2576,
          isRead: false,
          message: "#IN-2464749618 for $2200.00 has been submitted by Artigem",
          messageTemplate:
            "Invoice ${invoiceNumber} of ${invoiceAmount} is submitted for claim ${claimNumber} by vendor ${vendorName}",
          notificationParams: {
            isClaimNote: false,
            invoiceNumber: "IN-2464749618",
            invoiceId: 387,
            claimId: 1043,
            isItemNote: false,
            messageGrpId: null,
            claimNumber: "CLM9112024",
            quoteNumber: null,
            message1: "An Invoice Has Been Submitted",
          },
          notificationPurpose: "ITEM INVOICE",
          sender: null,
          subject: {
            id: 8,
            subject: "INVOICE_SUBMITTED",
          },
          type: {
            id: 1,
            type: "ALERT",
          },
          insuredDetails: {
            address: {
              city: null,
              completeAddress: "AZ, 87889",
              id: 2802,
              state: {
                id: 3,
                state: "AZ",
                stateName: null,
                taxRate: 8.25,
                timeZone: "(UTC-7:00) Mountain Standard Time (MST)",
                noOfZipcodesWrtState: null,
                premiumValueWrtState: null,
                hoPolicyTypes: null,
                noOfHOPolicyTypeState: null,
              },
              streetAddressOne: null,
              streetAddressTwo: null,
              zipcode: "87889",
            },
            secondaryAddress: null,
            agentDetails: null,
            cellPhone: null,
            extension: null,
            dayTimePhone: null,
            email: "xeyasa4986@undewp.com",
            secondaryEmail: null,
            eveningTimePhone: null,
            firstName: "Avinash",
            lastName: "Kumar",
            policyHolderId: 458,
            profilePicture: null,
            speedCheckVendorUrl: null,
            userRole: null,
            contactId: null,
          },
          page: null,
        },
        {
          createDate: "09 Nov 2023 09:10 PM",
          id: 2575,
          isRead: false,
          message: "#IN-1622936545 for $997.00 has been submitted by Artigem",
          messageTemplate:
            "Invoice ${invoiceNumber} of ${invoiceAmount} is submitted for claim ${claimNumber} by vendor ${vendorName}",
          notificationParams: {
            isClaimNote: false,
            invoiceNumber: "IN-1622936545",
            invoiceId: 386,
            claimId: 1043,
            isItemNote: false,
            messageGrpId: null,
            claimNumber: "CLM9112024",
            quoteNumber: null,
            message1: "An Invoice Has Been Submitted",
          },
          notificationPurpose: "ITEM INVOICE",
          sender: null,
          subject: {
            id: 8,
            subject: "INVOICE_SUBMITTED",
          },
          type: {
            id: 1,
            type: "ALERT",
          },
          insuredDetails: {
            address: {
              city: null,
              completeAddress: "AZ, 87889",
              id: 2802,
              state: {
                id: 3,
                state: "AZ",
                stateName: null,
                taxRate: 8.25,
                timeZone: "(UTC-7:00) Mountain Standard Time (MST)",
                noOfZipcodesWrtState: null,
                premiumValueWrtState: null,
                hoPolicyTypes: null,
                noOfHOPolicyTypeState: null,
              },
              streetAddressOne: null,
              streetAddressTwo: null,
              zipcode: "87889",
            },
            secondaryAddress: null,
            agentDetails: null,
            cellPhone: null,
            extension: null,
            dayTimePhone: null,
            email: "xeyasa4986@undewp.com",
            secondaryEmail: null,
            eveningTimePhone: null,
            firstName: "Avinash",
            lastName: "Kumar",
            policyHolderId: 458,
            profilePicture: null,
            speedCheckVendorUrl: null,
            userRole: null,
            contactId: null,
          },
          page: null,
        },
        {
          createDate: "09 Nov 2023 09:05 PM",
          id: 2574,
          isRead: false,
          message: "#IN-7179549518 for $1107.70 has been submitted by Artigem",
          messageTemplate:
            "Invoice ${invoiceNumber} of ${invoiceAmount} is submitted for claim ${claimNumber} by vendor ${vendorName}",
          notificationParams: {
            isClaimNote: false,
            invoiceNumber: "IN-7179549518",
            invoiceId: 385,
            claimId: 1043,
            isItemNote: false,
            messageGrpId: null,
            claimNumber: "CLM9112024",
            quoteNumber: null,
            message1: "An Invoice Has Been Submitted",
          },
          notificationPurpose: "ITEM INVOICE",
          sender: null,
          subject: {
            id: 8,
            subject: "INVOICE_SUBMITTED",
          },
          type: {
            id: 1,
            type: "ALERT",
          },
          insuredDetails: {
            address: {
              city: null,
              completeAddress: "AZ, 87889",
              id: 2802,
              state: {
                id: 3,
                state: "AZ",
                stateName: null,
                taxRate: 8.25,
                timeZone: "(UTC-7:00) Mountain Standard Time (MST)",
                noOfZipcodesWrtState: null,
                premiumValueWrtState: null,
                hoPolicyTypes: null,
                noOfHOPolicyTypeState: null,
              },
              streetAddressOne: null,
              streetAddressTwo: null,
              zipcode: "87889",
            },
            secondaryAddress: null,
            agentDetails: null,
            cellPhone: null,
            extension: null,
            dayTimePhone: null,
            email: "xeyasa4986@undewp.com",
            secondaryEmail: null,
            eveningTimePhone: null,
            firstName: "Avinash",
            lastName: "Kumar",
            policyHolderId: 458,
            profilePicture: null,
            speedCheckVendorUrl: null,
            userRole: null,
            contactId: null,
          },
          page: null,
        },
        {
          createDate: "09 Nov 2023 09:02 PM",
          id: 2573,
          isRead: false,
          message: "#IN-3304766631 for $4.40 has been submitted by Artigem",
          messageTemplate:
            "Invoice ${invoiceNumber} of ${invoiceAmount} is submitted for claim ${claimNumber} by vendor ${vendorName}",
          notificationParams: {
            isClaimNote: false,
            invoiceNumber: "IN-3304766631",
            invoiceId: 384,
            claimId: 1043,
            isItemNote: false,
            messageGrpId: null,
            claimNumber: "CLM9112024",
            quoteNumber: null,
            message1: "An Invoice Has Been Submitted",
          },
          notificationPurpose: "ITEM INVOICE",
          sender: null,
          subject: {
            id: 8,
            subject: "INVOICE_SUBMITTED",
          },
          type: {
            id: 1,
            type: "ALERT",
          },
          insuredDetails: {
            address: {
              city: null,
              completeAddress: "AZ, 87889",
              id: 2802,
              state: {
                id: 3,
                state: "AZ",
                stateName: null,
                taxRate: 8.25,
                timeZone: "(UTC-7:00) Mountain Standard Time (MST)",
                noOfZipcodesWrtState: null,
                premiumValueWrtState: null,
                hoPolicyTypes: null,
                noOfHOPolicyTypeState: null,
              },
              streetAddressOne: null,
              streetAddressTwo: null,
              zipcode: "87889",
            },
            secondaryAddress: null,
            agentDetails: null,
            cellPhone: null,
            extension: null,
            dayTimePhone: null,
            email: "xeyasa4986@undewp.com",
            secondaryEmail: null,
            eveningTimePhone: null,
            firstName: "Avinash",
            lastName: "Kumar",
            policyHolderId: 458,
            profilePicture: null,
            speedCheckVendorUrl: null,
            userRole: null,
            contactId: null,
          },
          page: null,
        },
        {
          createDate: "09 Nov 2023 05:24 PM",
          id: 2570,
          isRead: false,
          message: "#IN-5294551618 for $23284.21 has been submitted by Artigem",
          messageTemplate:
            "Invoice ${invoiceNumber} of ${invoiceAmount} is submitted for claim ${claimNumber} by vendor ${vendorName}",
          notificationParams: {
            isClaimNote: false,
            invoiceNumber: "IN-5294551618",
            invoiceId: 383,
            claimId: 1039,
            isItemNote: false,
            messageGrpId: null,
            claimNumber: "CLM9112023",
            quoteNumber: null,
            message1: "An Invoice Has Been Submitted",
          },
          notificationPurpose: "ITEM INVOICE",
          sender: null,
          subject: {
            id: 8,
            subject: "INVOICE_SUBMITTED",
          },
          type: {
            id: 1,
            type: "ALERT",
          },
          insuredDetails: {
            address: {
              city: "New Jersey",
              completeAddress: "4327 Finwood Road, Piscataway, New Jersey, NJ, 08854",
              id: 85,
              state: {
                id: 31,
                state: "NJ",
                stateName: null,
                taxRate: 6.85,
                timeZone: "(UTC-5:00) Eastern Standard Time (EST)",
                noOfZipcodesWrtState: null,
                premiumValueWrtState: null,
                hoPolicyTypes: null,
                noOfHOPolicyTypeState: null,
              },
              streetAddressOne: "4327 Finwood Road",
              streetAddressTwo: "Piscataway",
              zipcode: "08854",
            },
            secondaryAddress: null,
            agentDetails: null,
            cellPhone: null,
            extension: null,
            dayTimePhone: null,
            email: "policy.holder@sakhaglobal.com",
            secondaryEmail: null,
            eveningTimePhone: null,
            firstName: "Gracie",
            lastName: "Smith",
            policyHolderId: 29,
            profilePicture: null,
            speedCheckVendorUrl: null,
            userRole: null,
            contactId: null,
          },
          page: null,
        },
        {
          createDate: "09 Nov 2023 05:24 PM",
          id: 2569,
          isRead: false,
          message: "#IN-5023669286 for $23282.21 has been submitted by Artigem",
          messageTemplate:
            "Invoice ${invoiceNumber} of ${invoiceAmount} is submitted for claim ${claimNumber} by vendor ${vendorName}",
          notificationParams: {
            isClaimNote: false,
            invoiceNumber: "IN-5023669286",
            invoiceId: 382,
            claimId: 1039,
            isItemNote: false,
            messageGrpId: null,
            claimNumber: "CLM9112023",
            quoteNumber: null,
            message1: "An Invoice Has Been Submitted",
          },
          notificationPurpose: "ITEM INVOICE",
          sender: null,
          subject: {
            id: 8,
            subject: "INVOICE_SUBMITTED",
          },
          type: {
            id: 1,
            type: "ALERT",
          },
          insuredDetails: {
            address: {
              city: "New Jersey",
              completeAddress: "4327 Finwood Road, Piscataway, New Jersey, NJ, 08854",
              id: 85,
              state: {
                id: 31,
                state: "NJ",
                stateName: null,
                taxRate: 6.85,
                timeZone: "(UTC-5:00) Eastern Standard Time (EST)",
                noOfZipcodesWrtState: null,
                premiumValueWrtState: null,
                hoPolicyTypes: null,
                noOfHOPolicyTypeState: null,
              },
              streetAddressOne: "4327 Finwood Road",
              streetAddressTwo: "Piscataway",
              zipcode: "08854",
            },
            secondaryAddress: null,
            agentDetails: null,
            cellPhone: null,
            extension: null,
            dayTimePhone: null,
            email: "policy.holder@sakhaglobal.com",
            secondaryEmail: null,
            eveningTimePhone: null,
            firstName: "Gracie",
            lastName: "Smith",
            policyHolderId: 29,
            profilePicture: null,
            speedCheckVendorUrl: null,
            userRole: null,
            contactId: null,
          },
          page: null,
        },
        {
          createDate: "09 Nov 2023 03:46 PM",
          id: 2568,
          isRead: false,
          message: "#IN-8196917748 for $404.00 has been submitted by Artigem",
          messageTemplate:
            "Invoice ${invoiceNumber} of ${invoiceAmount} is submitted for claim ${claimNumber} by vendor ${vendorName}",
          notificationParams: {
            isClaimNote: false,
            invoiceNumber: "IN-8196917748",
            invoiceId: 381,
            claimId: 1039,
            isItemNote: false,
            messageGrpId: null,
            claimNumber: "CLM9112023",
            quoteNumber: null,
            message1: "An Invoice Has Been Submitted",
          },
          notificationPurpose: "ITEM INVOICE",
          sender: null,
          subject: {
            id: 8,
            subject: "INVOICE_SUBMITTED",
          },
          type: {
            id: 1,
            type: "ALERT",
          },
          insuredDetails: {
            address: {
              city: "New Jersey",
              completeAddress: "4327 Finwood Road, Piscataway, New Jersey, NJ, 08854",
              id: 85,
              state: {
                id: 31,
                state: "NJ",
                stateName: null,
                taxRate: 6.85,
                timeZone: "(UTC-5:00) Eastern Standard Time (EST)",
                noOfZipcodesWrtState: null,
                premiumValueWrtState: null,
                hoPolicyTypes: null,
                noOfHOPolicyTypeState: null,
              },
              streetAddressOne: "4327 Finwood Road",
              streetAddressTwo: "Piscataway",
              zipcode: "08854",
            },
            secondaryAddress: null,
            agentDetails: null,
            cellPhone: null,
            extension: null,
            dayTimePhone: null,
            email: "policy.holder@sakhaglobal.com",
            secondaryEmail: null,
            eveningTimePhone: null,
            firstName: "Gracie",
            lastName: "Smith",
            policyHolderId: 29,
            profilePicture: null,
            speedCheckVendorUrl: null,
            userRole: null,
            contactId: null,
          },
          page: null,
        },
      ],
      totalCount: 98,
    },
    message: "Dashboard notification list.",
    status: 200,
  },
];

export const sampleNewClaims = {
  data: {
    adjuster: null,
    adjusterCoverageLimit: null,
    claims: null,
    numberOfClaimHandle: 0,
    numberOfItemHandle: 0,
    replacement: null,
    avgClosingClaim: "",
    openClaims: 25,
    newClaims: 25,
    closedClaims: 0,
    totalInvoices: null,
  },
  message: "successfully fetched data",
  status: 200,
};

export const sampleNewClaimsThisQuater = {
  data: {
    adjuster: null,
    adjusterCoverageLimit: null,
    claims: null,
    numberOfClaimHandle: 0,
    numberOfItemHandle: 0,
    replacement: null,
    avgClosingClaim: "2 D 23 H 25 M ",
    openClaims: 106,
    newClaims: 107,
    closedClaims: 1,
    totalInvoices: null,
  },
  message: "successfully fetched data",
  status: 200,
};

export const sampleNewClaimsThisYear = {
  data: {
    adjuster: null,
    adjusterCoverageLimit: null,
    claims: null,
    numberOfClaimHandle: 0,
    numberOfItemHandle: 0,
    replacement: null,
    avgClosingClaim: "2 D 23 H 25 M ",
    openClaims: 165,
    newClaims: 166,
    closedClaims: 1,
    totalInvoices: null,
  },
  message: "successfully fetched data",
  status: 200,
};
