import { unknownObjectType } from "./customTypes";

export const managerRoleMaping: unknownObjectType = {
  1001: ["INSURANCE COMPANY ADMINISTRATOR"],
  1002: ["INSURANCE COMPANY ADMINISTRATOR"],
  1003: ["CLAIM MANAGER"],
  1004: ["INSURANCE ACCOUNT MANAGER"],
  1005: ["CLAIM SUPERVISOR", "CLAIM MANAGER"],
  1006: ["CLAIM SUPERVISOR", "CLAIM MANAGER"],
  1007: ["INSURANCE ACCOUNT MANAGER"],
  1008: ["CLAIM SUPERVISOR", "CLAIM MANAGER"],
  1009: ["CLAIM CENTER ADMIN"],
  1010: ["POLICYHOLDER"],
  1011: ["INSURED"],
  1012: ["NA"],
  1013: ["INSURANCE COMPANY ADMINISTRATOR"],
};
